before:
  hooks:
    - go mod tidy
builds:
  - ldflags:
      - -X 'main.buildVersion={{.Version}}'
    env:
      - CGO_ENABLED=0
    # https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386 
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: 386
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: 386
archives:
  - replacements:
      386: i386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
