name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - run: echo "IMAGE_TAG=${GITHUB_ACTOR}" >> $GITHUB_ENV

    - run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG} .

    - run: make build